stages:
  - test

.phpcode: &phpcode
  stage: test
  image: registry.zendovo.eu/netleak/dockers/php:7.4-xdebug
  before_script:
    - composer install --prefer-dist -o
  cache:
    paths:
      - vendor/

code:check:
  <<: *phpcode
  script:
    - vendor/bin/phpcs
    - vendor/bin/phpstan analyse --no-progress
